---
# tasks file for ansible-yapkg
- name: 'install {{ yapkg_task_group_name }}'
  become: True
  apt:
    name: '{{ yapkg_names | reject("equalto", "") | list() }}'
    update_cache: '{{ yapkg_update_cache }}'
    cache_valid_time: '{{ yapkg_cache_valid_time }}'
  when:
   - yapkg_target_release == ""
   - yapkg_names is iterable
   - not yapkg_names is string
   - ansible_pkg_mgr == "apt"

- name: 'install {{ yapkg_task_group_name }}'
  become: True
  apt:
    name: '{{ yapkg_names | reject("equalto", "") | list() }}'
    default_release: '{{ yapkg_target_release }}'
    update_cache: '{{ yapkg_update_cache }}'
    cache_valid_time: '{{ yapkg_cache_valid_time }}'
  when:
   - yapkg_target_release != ""
   - yapkg_names is iterable
   - not yapkg_names is string
   - ansible_pkg_mgr == "apt"

