---
# tasks file for ansible-yapkg
- name: 'install {{ yapkg_task_group_name }}'
  apt:
    name: '{{ item }}'
    update_cache: '{{ yapkg_update_cache }}'
    cache_valid_time: '{{ yapkg_cache_valid_time }}'
  with_items: '{{ yapkg_names }}'
  when:
   - yapkg_target_release == ""
   - yapkg_names is iterable
   - not yapkg_names is string
   - ansible_os_family == "Debian"

- name: 'install {{ yapkg_task_group_name }}'
  apt:
    name: '{{ item }}'
    default_release: '{{ yapkg_target_release }}'
    update_cache: '{{ yapkg_update_cache }}'
    cache_valid_time: '{{ yapkg_cache_valid_time }}'
  with_items: '{{ yapkg_names }}'
  when:
   - yapkg_target_release != ""
   - yapkg_names is iterable
   - not yapkg_names is string
   - ansible_os_family == "Debian"

